database:
  url: http://localhost:8050

profile:
  url: http://localhost:8040

deposit:
  url: http://localhost:8081

transfer:
  url: http://localhost:8082

frontend:
  url: http://localhost:8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: 11111111
    driver-class-name: org.postgresql.Driver

