server:
  port: 8081

spring:
  application:
    name: deposit

database:
  url: http://localhost:8050

management:
  endpoints:
    web:
      exposure:
        include: health, deposit, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true